package tk.michael.project;/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

import tk.michael.project.DatabaseBox;

/**
 * @author Michael
 */
public class MainWindow extends javax.swing.JFrame {

	/**
	 * Creates new form MainWindow
	 */
	public MainWindow() {
		initComponents();

		jPanel1.setLayout( new WrapLayout() );
		jPanel1.add( new DatabaseBox() );
		jPanel1.add( new DatabaseBox() );
		jPanel1.add( new DatabaseBox() );
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jPanel1 = new javax.swing.JPanel();
		jMenuBar1 = new javax.swing.JMenuBar();
		jMenu1 = new javax.swing.JMenu();
		jMenu2 = new javax.swing.JMenu();

		setDefaultCloseOperation( javax.swing.WindowConstants.EXIT_ON_CLOSE );
		setBackground( new java.awt.Color( 0, 0, 0 ) );
		setCursor( new java.awt.Cursor( java.awt.Cursor.DEFAULT_CURSOR ) );
		setForeground( java.awt.Color.white );

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout( jPanel1 );
		jPanel1.setLayout( jPanel1Layout );
		jPanel1Layout.setHorizontalGroup(
			jPanel1Layout.createParallelGroup( javax.swing.GroupLayout.Alignment.LEADING )
				.addGap( 0, 620, Short.MAX_VALUE )
		);
		jPanel1Layout.setVerticalGroup(
			jPanel1Layout.createParallelGroup( javax.swing.GroupLayout.Alignment.LEADING )
				.addGap( 0, 424, Short.MAX_VALUE )
		);

		jMenu1.setText( "File" );
		jMenuBar1.add( jMenu1 );

		jMenu2.setText( "Edit" );
		jMenuBar1.add( jMenu2 );

		setJMenuBar( jMenuBar1 );

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout( getContentPane() );
		getContentPane().setLayout( layout );
		layout.setHorizontalGroup(
			layout.createParallelGroup( javax.swing.GroupLayout.Alignment.LEADING )
				.addComponent( jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE )
		);
		layout.setVerticalGroup(
			layout.createParallelGroup( javax.swing.GroupLayout.Alignment.LEADING )
				.addComponent( jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE )
		);

		pack();
	}// </editor-fold>//GEN-END:initComponents

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JMenu jMenu1;
	private javax.swing.JMenu jMenu2;
	private javax.swing.JMenuBar jMenuBar1;
	private javax.swing.JPanel jPanel1;
	// End of variables declaration//GEN-END:variables
}
