/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Michael
 */
public class DatabaseBox extends javax.swing.JPanel {

    /**
     * Creates new form DatabaseBox
     */
    public DatabaseBox() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dbName1 = new javax.swing.JLabel();
        dbTitle = new javax.swing.JLabel();
        dbUser = new javax.swing.JLabel();
        dbName = new javax.swing.JLabel();
        dbHost = new javax.swing.JLabel();

        dbName1.setBackground(new java.awt.Color(153, 153, 153));
        dbName1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        dbName1.setForeground(new java.awt.Color(204, 204, 204));
        dbName1.setText("Database Name");

        setBackground(new java.awt.Color(102, 102, 102));

        dbTitle.setBackground(new java.awt.Color(153, 153, 153));
        dbTitle.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        dbTitle.setForeground(new java.awt.Color(204, 204, 204));
        dbTitle.setText("Database Title");
        dbTitle.setToolTipText("");

        dbUser.setBackground(new java.awt.Color(153, 153, 153));
        dbUser.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        dbUser.setForeground(new java.awt.Color(204, 204, 204));
        dbUser.setText("Database user");

        dbName.setBackground(new java.awt.Color(153, 153, 153));
        dbName.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        dbName.setForeground(new java.awt.Color(204, 204, 204));
        dbName.setText("Database Name");

        dbHost.setBackground(new java.awt.Color(153, 153, 153));
        dbHost.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        dbHost.setForeground(new java.awt.Color(204, 204, 204));
        dbHost.setText("Database Host");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dbTitle)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(dbUser)
                        .addGap(47, 47, 47)
                        .addComponent(dbName))
                    .addComponent(dbHost))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dbTitle)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dbUser)
                    .addComponent(dbName))
                .addGap(18, 18, 18)
                .addComponent(dbHost)
                .addContainerGap(21, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel dbHost;
    private javax.swing.JLabel dbName;
    private javax.swing.JLabel dbName1;
    private javax.swing.JLabel dbTitle;
    private javax.swing.JLabel dbUser;
    // End of variables declaration//GEN-END:variables
}
